# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computeEkin(m=None,vel=None,*args,**kwargs):
    varargin = computeEkin.varargin
    nargin = computeEkin.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 2nd, 2014
#    Last update: July 2nd, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    Ekinpdof=multiply(0.5,vel ** 2.0) / cat(m,m,m)
    Ekinp=multiply(0.5,sum(vel ** 2,2)) / m
    Ekin=multiply(0.5,sum(sum(vel ** 2,2))) / m
    return Ekinpdof,Ekinp,Ekin