# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def bending_spring(elasticparam=None,t=None,points=None,lattice=None,*args,**kwargs):
    varargin = bending_spring.varargin
    nargin = bending_spring.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: August 4th, 2014
#    Last update: August 4th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    k=elasticparam[1]
    return k