# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def evaluateexternalforces2D(t=None,lattice=None,vel=None,fexthandle=None,*args,**kwargs):
    varargin = evaluateexternalforces2D.varargin
    nargin = evaluateexternalforces2D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 14th, 2014
#    Last update: July 14th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    F=fexthandle[lattice[:,5:6],vel,t]
    return F