# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def evaluateelasticforces3D(t=None,N=None,lattice=None,elasticparam=None,ksthandle=None,kshhandle=None,kbehandle=None,structuralneighbours=None,shearneighbours=None,bendneighbours=None,*args,**kwargs):
    varargin = evaluateelasticforces3D.varargin
    nargin = evaluateelasticforces3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: June 26th, 2014
#    Last update: August 4th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    Fel=zeros(N,3)
    ##
    
    # ---> structural springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,6).reshape(-1):
            neigh=structuralneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(ksthandle[elasticparam,t,dot(0.5,(lattice[neigh,7:9] + lattice[i,7:9])),lattice],(1 - (sqrt(sum((lattice[neigh,4:6] - lattice[i,4:6]) ** 2,2))) / (sqrt(sum((lattice[neigh,7:9] - lattice[i,7:9]) ** 2,2))))),(lattice[neigh,7:9] - lattice[i,7:9]))
    
    # ---> shear springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,20).reshape(-1):
            neigh=shearneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(kshhandle[elasticparam,t,dot(0.5,(lattice[neigh,7:9] + lattice[i,7:9])),lattice],(1 - (sqrt(sum((lattice[neigh,4:6] - lattice[i,4:6]) ** 2,2))) / (sqrt(sum((lattice[neigh,7:9] - lattice[i,7:9]) ** 2,2))))),(lattice[neigh,7:9] - lattice[i,7:9]))
    
    # ---> bend springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,6).reshape(-1):
            neigh=bendneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(kbehandle[elasticparam,t,dot(0.5,(lattice[neigh,7:9] + lattice[i,7:9])),lattice],(1 - (sqrt(sum((lattice[neigh,4:6] - lattice[i,4:6]) ** 2,2))) / (sqrt(sum((lattice[neigh,7:9] - lattice[i,7:9]) ** 2,2))))),(lattice[neigh,7:9] - lattice[i,7:9]))
    
    return Fel