# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def evaluateelasticforces2D(t=None,N=None,lattice=None,elasticparam=None,ksthandle=None,kshhandle=None,kbehandle=None,structuralneighbours=None,shearneighbours=None,bendneighbours=None,*args,**kwargs):
    varargin = evaluateelasticforces2D.varargin
    nargin = evaluateelasticforces2D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 14th, 2014
#    Last update: August 4th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    Fel=zeros(N,2)
    ##
    
    # ---> structural springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,4).reshape(-1):
            neigh=structuralneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(ksthandle[elasticparam,t,dot(0.5,(lattice[neigh,5:6] + lattice[i,5:6])),lattice],(1 - (sqrt(sum((lattice[neigh,3:4] - lattice[i,3:4]) ** 2,2))) / (sqrt(sum((lattice[neigh,5:6] - lattice[i,5:6]) ** 2,2))))),(lattice[neigh,5:6] - lattice[i,5:6]))
    
    # ---> shear springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,4).reshape(-1):
            neigh=shearneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(kshhandle[elasticparam,t,dot(0.5,(lattice[neigh,5:6] + lattice[i,5:6])),lattice],(1 - (sqrt(sum((lattice[neigh,3:4] - lattice[i,3:4]) ** 2,2))) / (sqrt(sum((lattice[neigh,5:6] - lattice[i,5:6]) ** 2,2))))),(lattice[neigh,5:6] - lattice[i,5:6]))
    
    # ---> bend springs
    
    for i in arange(1,N).reshape(-1):
        for j in arange(1,4).reshape(-1):
            neigh=bendneighbours[i,j + 1]
            if neigh != - 1:
                Fel[i,:]=Fel[i,:] + multiply(multiply(kbehandle[elasticparam,t,dot(0.5,(lattice[neigh,5:6] + lattice[i,5:6])),lattice],(1 - (sqrt(sum((lattice[neigh,3:4] - lattice[i,3:4]) ** 2,2))) / (sqrt(sum((lattice[neigh,5:6] - lattice[i,5:6]) ** 2,2))))),(lattice[neigh,5:6] - lattice[i,5:6]))
    
    return Fel