# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def nullfext(pos=None,vel=None,t=None,*args,**kwargs):
    varargin = nullfext.varargin
    nargin = nullfext.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 29th, 2014
#    Last update: July 29th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    N=size(pos,1)
    F=sparse(cat([(arange(1,N)).T],[(arange(1,N)).T],[(arange(1,N)).T]),cat([ones(N,1)],[dot(2,ones(N,1))],[dot(3,ones(N,1))]),zeros(dot(3,N),1),N,3)
    return F